#!/usr/bin/env python3
"""Siri intent descriptions, spoken dialogs, and entity labels for all catalog locales."""

from __future__ import annotations

# Intent descriptions, dialogs, entity type names used by App Intents / Siri.
SIRI_DIALOG_STRINGS: dict[str, dict[str, str]] = {
    "Add a movie or TV show to your Cronica watchlist.": {
        "en": "Add a movie or TV show to your Cronica watchlist.",
        "de": "Füge einen Film oder eine Serie zu deiner Cronica-Watchlist hinzu.",
        "fr": "Ajoutez un film ou une série à votre liste Cronica.",
        "it": "Aggiungi un film o una serie alla watchlist di Cronica.",
        "pt-BR": "Adicione um filme ou série à sua lista do Cronica.",
        "sk": "Pridajte film alebo seriál do zoznamu Cronica.",
        "es-MX": "Agrega una película o serie a tu lista de Cronica.",
        "es": "Añade una película o serie a tu lista de Cronica.",
        "ar": "أضف فيلمًا أو مسلسلًا إلى قائمة المشاهدة في Cronica.",
        "cs": "Přidejte film nebo seriál do seznamu Cronica.",
        "da": "Tilføj en film eller serie til din Cronica-watchlist.",
        "el": "Πρόσθεσε μια ταινία ή σειρά στη λίστα του Cronica.",
        "fi": "Lisää elokuva tai sarja Cronican katselulistaan.",
        "he": "הוסף סרט או סדרה לרשימת הצפייה של Cronica.",
        "hi": "Cronica वॉचलिस्ट में कोई फ़िल्म या शो जोड़ें।",
        "hr": "Dodaj film ili seriju na Cronica listu.",
        "hu": "Adj filmet vagy sorozatot a Cronica listádhoz.",
        "id": "Tambahkan film atau acara ke watchlist Cronica Anda.",
        "ja": "映画やドラマをCronicaのウォッチリストに追加します。",
        "ko": "영화나 TV 프로그램을 Cronica 관심 목록에 추가합니다.",
        "ms": "Tambah filem atau rancangan ke senarai tontonan Cronica anda.",
        "nb": "Legg til en film eller serie i Cronica-ønskelisten din.",
        "nl": "Voeg een film of serie toe aan je Cronica-watchlist.",
        "pl": "Dodaj film lub serial do listy Cronica.",
        "ro": "Adaugă un film sau un serial pe lista Cronica.",
        "ru": "Добавьте фильм или сериал в список Cronica.",
        "sv": "Lägg till en film eller serie i din Cronica-watchlist.",
        "tr": "Cronica izleme listenize bir film veya dizi ekleyin.",
        "uk": "Додайте фільм або серіал до списку Cronica.",
        "zh-Hans": "将电影或剧集添加到 Cronica 片单。",
        "zh-Hant": "將電影或劇集加入 Cronica 片單。",
    },
    "Remove a title from your Cronica watchlist.": {
        "en": "Remove a title from your Cronica watchlist.",
        "de": "Entferne einen Titel von deiner Cronica-Watchlist.",
        "fr": "Retirez un titre de votre liste Cronica.",
        "it": "Rimuovi un titolo dalla watchlist di Cronica.",
        "pt-BR": "Remova um título da sua lista do Cronica.",
        "sk": "Odstráňte titul zo zoznamu Cronica.",
        "es-MX": "Quita un título de tu lista de Cronica.",
        "es": "Quita un título de tu lista de Cronica.",
        "ar": "أزل عنوانًا من قائمة المشاهدة في Cronica.",
        "cs": "Odeberte titul ze seznamu Cronica.",
        "da": "Fjern en titel fra din Cronica-watchlist.",
        "el": "Αφαίρεσε έναν τίτλο από τη λίστα του Cronica.",
        "fi": "Poista nimi Cronican katselulistasta.",
        "he": "הסר כותרת מרשימת הצפייה של Cronica.",
        "hi": "Cronica वॉचलिस्ट से कोई शीर्षक हटाएं।",
        "hr": "Ukloni naslov s Cronica liste.",
        "hu": "Távolíts el egy címet a Cronica listádról.",
        "id": "Hapus judul dari watchlist Cronica Anda.",
        "ja": "Cronicaのウォッチリストから作品を削除します。",
        "ko": "Cronica 관심 목록에서 작품을 제거합니다.",
        "ms": "Buang tajuk dari senarai tontonan Cronica anda.",
        "nb": "Fjern en tittel fra Cronica-ønskelisten din.",
        "nl": "Verwijder een titel uit je Cronica-watchlist.",
        "pl": "Usuń tytuł z listy Cronica.",
        "ro": "Elimină un titlu de pe lista Cronica.",
        "ru": "Удалите название из списка Cronica.",
        "sv": "Ta bort en titel från din Cronica-watchlist.",
        "tr": "Cronica izleme listenizden bir yapımı kaldırın.",
        "uk": "Видаліть назву зі списку Cronica.",
        "zh-Hans": "从 Cronica 片单中移除作品。",
        "zh-Hant": "從 Cronica 片單移除作品。",
    },
    "Mark a movie or TV show as watched in Cronica.": {
        "en": "Mark a movie or TV show as watched in Cronica.",
        "de": "Markiere einen Film oder eine Serie in Cronica als gesehen.",
        "fr": "Marquez un film ou une série comme vu dans Cronica.",
        "it": "Segna un film o una serie come visto in Cronica.",
        "pt-BR": "Marque um filme ou série como assistido no Cronica.",
        "sk": "Označte film alebo seriál ako pozretý v Cronica.",
        "es-MX": "Marca una película o serie como vista en Cronica.",
        "es": "Marca una película o serie como vista en Cronica.",
        "ar": "علّم فيلمًا أو مسلسلًا كمشاهَد في Cronica.",
        "cs": "Označte film nebo seriál jako zhlédnutý v Cronica.",
        "da": "Markér en film eller serie som set i Cronica.",
        "el": "Μάρκαρε μια ταινία ή σειρά ως προβληθείσα στο Cronica.",
        "fi": "Merkitse elokuva tai sarja katsotuksi Cronicassa.",
        "he": "סמן סרט או סדרה כנצפים ב־Cronica.",
        "hi": "Cronica में किसी फ़िल्म या शो को देखा गया चिह्नित करें।",
        "hr": "Označi film ili seriju kao pogledane u Cronica.",
        "hu": "Jelölj filmet vagy sorozatot megnézettként a Cronicában.",
        "id": "Tandai film atau acara sebagai ditonton di Cronica.",
        "ja": "Cronicaで映画やドラマを視聴済みにします。",
        "ko": "Cronica에서 영화나 TV 프로그램을 시청함으로 표시합니다.",
        "ms": "Tanda filem atau rancangan sebagai ditonton dalam Cronica.",
        "nb": "Merk en film eller serie som sett i Cronica.",
        "nl": "Markeer een film of serie als bekeken in Cronica.",
        "pl": "Oznacz film lub serial jako obejrzany w Cronica.",
        "ro": "Marchează un film sau un serial ca vizionat în Cronica.",
        "ru": "Отметьте фильм или сериал как просмотренный в Cronica.",
        "sv": "Markera en film eller serie som sett i Cronica.",
        "tr": "Cronica’da bir film veya diziyi izlendi olarak işaretleyin.",
        "uk": "Позначте фільм або серіал як переглянутий у Cronica.",
        "zh-Hans": "在 Cronica 中将电影或剧集标记为已看。",
        "zh-Hant": "在 Cronica 中將電影或劇集標記為已看。",
    },
    "Mark your next episode as watched in Cronica.": {
        "en": "Mark your next episode as watched in Cronica.",
        "de": "Markiere deine nächste Episode in Cronica als gesehen.",
        "fr": "Marquez votre prochain épisode comme vu dans Cronica.",
        "it": "Segna il prossimo episodio come visto in Cronica.",
        "pt-BR": "Marque seu próximo episódio como assistido no Cronica.",
        "sk": "Označte ďalšiu epizódu ako pozretú v Cronica.",
        "es-MX": "Marca tu próximo episodio como visto en Cronica.",
        "es": "Marca tu próximo episodio como visto en Cronica.",
        "ar": "علّم حلقتك التالية كمشاهَدة في Cronica.",
        "cs": "Označte další epizodu jako zhlédnutou v Cronica.",
        "da": "Markér din næste episode som set i Cronica.",
        "el": "Μάρκαρε το επόμενο επεισόδιό σου ως προβληθέν στο Cronica.",
        "fi": "Merkitse seuraava jaksosi katsotuksi Cronicassa.",
        "he": "סמן את הפרק הבא שלך כנצפה ב־Cronica.",
        "hi": "Cronica में अपना अगला एपिसोड देखा गया चिह्नित करें।",
        "hr": "Označi sljedeću epizodu kao pogledanu u Cronica.",
        "hu": "Jelöld megnézettként a következő epizódodat a Cronicában.",
        "id": "Tandai episode berikutnya sebagai ditonton di Cronica.",
        "ja": "Cronicaで次のエピソードを視聴済みにします。",
        "ko": "Cronica에서 다음 에피소드를 시청함으로 표시합니다.",
        "ms": "Tanda episod seterusnya anda sebagai ditonton dalam Cronica.",
        "nb": "Merk neste episode som sett i Cronica.",
        "nl": "Markeer je volgende aflevering als bekeken in Cronica.",
        "pl": "Oznacz kolejny odcinek jako obejrzany w Cronica.",
        "ro": "Marchează următorul episod ca vizionat în Cronica.",
        "ru": "Отметьте следующий эпизод как просмотренный в Cronica.",
        "sv": "Markera ditt nästa avsnitt som sett i Cronica.",
        "tr": "Cronica’da sonraki bölümünüzü izlendi olarak işaretleyin.",
        "uk": "Позначте наступний епізод як переглянутий у Cronica.",
        "zh-Hans": "在 Cronica 中将下一集标记为已看。",
        "zh-Hant": "在 Cronica 中將下一集標記為已看。",
    },
    "See what episodes are up next in Cronica.": {
        "en": "See what episodes are up next in Cronica.",
        "de": "Sieh, welche Episoden in Cronica als Nächstes kommen.",
        "fr": "Voyez quels épisodes sont à suivre dans Cronica.",
        "it": "Vedi quali episodi sono in programma in Cronica.",
        "pt-BR": "Veja quais episódios vêm a seguir no Cronica.",
        "sk": "Pozrite, ktoré epizódy sú ďalej v Cronica.",
        "es-MX": "Mira qué episodios siguen en Cronica.",
        "es": "Mira qué episodios hay a continuación en Cronica.",
        "ar": "اطلع على الحلقات التالية في Cronica.",
        "cs": "Podívejte se, které epizody jsou další v Cronica.",
        "da": "Se hvilke episoder der er næste i Cronica.",
        "el": "Δες ποια επεισόδια ακολουθούν στο Cronica.",
        "fi": "Katso, mitkä jaksot ovat seuraavaksi Cronicassa.",
        "he": "ראה אילו פרקים הבאים בתור ב־Cronica.",
        "hi": "Cronica में आगे कौन से एपिसोड हैं देखें।",
        "hr": "Pogledaj koje epizode slijede u Cronica.",
        "hu": "Nézd meg, milyen epizódok következnek a Cronicában.",
        "id": "Lihat episode apa yang selanjutnya di Cronica.",
        "ja": "Cronicaで次に観るエピソードを確認します。",
        "ko": "Cronica에서 다음에 볼 에피소드를 확인합니다.",
        "ms": "Lihat episod seterusnya dalam Cronica.",
        "nb": "Se hvilke episoder som er neste i Cronica.",
        "nl": "Bekijk welke afleveringen hierna komen in Cronica.",
        "pl": "Zobacz, które odcinki są dalej w Cronica.",
        "ro": "Vezi ce episoade urmează în Cronica.",
        "ru": "Посмотрите, какие эпизоды дальше в Cronica.",
        "sv": "Se vilka avsnitt som är nästa i Cronica.",
        "tr": "Cronica’da sıradaki bölümleri görün.",
        "uk": "Подивіться, які епізоди далі в Cronica.",
        "zh-Hans": "查看 Cronica 中接下来的剧集。",
        "zh-Hant": "查看 Cronica 中接下來的劇集。",
    },
    "Open Cronica search to find movies and TV shows.": {
        "en": "Open Cronica search to find movies and TV shows.",
        "de": "Öffne die Cronica-Suche, um Filme und Serien zu finden.",
        "fr": "Ouvrez la recherche Cronica pour trouver films et séries.",
        "it": "Apri la ricerca di Cronica per trovare film e serie.",
        "pt-BR": "Abra a pesquisa do Cronica para encontrar filmes e séries.",
        "sk": "Otvorte vyhľadávanie Cronica a nájdite filmy a seriály.",
        "es-MX": "Abre la búsqueda de Cronica para encontrar películas y series.",
        "es": "Abre la búsqueda de Cronica para encontrar películas y series.",
        "ar": "افتح بحث Cronica للعثور على أفلام ومسلسلات.",
        "cs": "Otevřete hledání Cronica a najděte filmy a seriály.",
        "da": "Åbn Cronica-søgning for at finde film og serier.",
        "el": "Άνοιξε την αναζήτηση Cronica για ταινίες και σειρές.",
        "fi": "Avaa Cronican haku elokuvien ja sarjojen löytämiseksi.",
        "he": "פתח את החיפוש ב־Cronica כדי למצוא סרטים וסדרות.",
        "hi": "फ़िल्में और शो खोजने के लिए Cronica खोज खोलें।",
        "hr": "Otvori Cronica pretraživanje za filmove i serije.",
        "hu": "Nyisd meg a Cronica keresőt filmekhez és sorozatokhoz.",
        "id": "Buka pencarian Cronica untuk menemukan film dan acara.",
        "ja": "Cronicaの検索を開いて映画やドラマを探します。",
        "ko": "Cronica 검색을 열어 영화와 TV 프로그램을 찾습니다.",
        "ms": "Buka carian Cronica untuk mencari filem dan rancangan.",
        "nb": "Åpne Cronica-søk for å finne filmer og serier.",
        "nl": "Open Zoeken in Cronica om films en series te vinden.",
        "pl": "Otwórz wyszukiwanie Cronica, aby znaleźć filmy i seriale.",
        "ro": "Deschide căutarea Cronica pentru filme și seriale.",
        "ru": "Откройте поиск Cronica, чтобы найти фильмы и сериалы.",
        "sv": "Öppna Cronica-sökning för att hitta filmer och serier.",
        "tr": "Film ve dizi bulmak için Cronica aramasını açın.",
        "uk": "Відкрийте пошук Cronica, щоб знайти фільми та серіали.",
        "zh-Hans": "打开 Cronica 搜索以查找电影和剧集。",
        "zh-Hant": "打開 Cronica 搜尋以尋找電影和劇集。",
    },
    "Search for movies and TV shows in Cronica.": {
        "en": "Search for movies and TV shows in Cronica.",
        "de": "Suche in Cronica nach Filmen und Serien.",
        "fr": "Recherchez des films et des séries dans Cronica.",
        "it": "Cerca film e serie in Cronica.",
        "pt-BR": "Pesquise filmes e séries no Cronica.",
        "sk": "Hľadajte filmy a seriály v Cronica.",
        "es-MX": "Busca películas y series en Cronica.",
        "es": "Busca películas y series en Cronica.",
        "ar": "ابحث عن أفلام ومسلسلات في Cronica.",
        "cs": "Hledejte filmy a seriály v Cronica.",
        "da": "Søg efter film og serier i Cronica.",
        "el": "Αναζήτησε ταινίες και σειρές στο Cronica.",
        "fi": "Etsi elokuvia ja sarjoja Cronicasta.",
        "he": "חפש סרטים וסדרות ב־Cronica.",
        "hi": "Cronica में फ़िल्में और शो खोजें।",
        "hr": "Traži filmove i serije u Cronica.",
        "hu": "Keress filmeket és sorozatokat a Cronicában.",
        "id": "Cari film dan acara di Cronica.",
        "ja": "Cronicaで映画やドラマを検索します。",
        "ko": "Cronica에서 영화와 TV 프로그램을 검색합니다.",
        "ms": "Cari filem dan rancangan dalam Cronica.",
        "nb": "Søk etter filmer og serier i Cronica.",
        "nl": "Zoek films en series in Cronica.",
        "pl": "Szukaj filmów i seriali w Cronica.",
        "ro": "Caută filme și seriale în Cronica.",
        "ru": "Ищите фильмы и сериалы в Cronica.",
        "sv": "Sök efter filmer och serier i Cronica.",
        "tr": "Cronica’da film ve dizi arayın.",
        "uk": "Шукайте фільми та серіали в Cronica.",
        "zh-Hans": "在 Cronica 中搜索电影和剧集。",
        "zh-Hant": "在 Cronica 中搜尋電影和劇集。",
    },
    "Add a movie or TV show to your watchlist from a shared link.": {
        "en": "Add a movie or TV show to your watchlist from a shared link.",
        "de": "Füge einen Film oder eine Serie über einen geteilten Link zur Watchlist hinzu.",
        "fr": "Ajoutez un film ou une série à votre liste depuis un lien partagé.",
        "it": "Aggiungi un film o una serie alla watchlist da un link condiviso.",
        "pt-BR": "Adicione um filme ou série à lista a partir de um link compartilhado.",
        "sk": "Pridajte film alebo seriál do zoznamu zo zdieľaného odkazu.",
        "es-MX": "Agrega una película o serie a tu lista desde un enlace compartido.",
        "es": "Añade una película o serie a tu lista desde un enlace compartido.",
        "ar": "أضف فيلمًا أو مسلسلًا إلى قائمة المشاهدة من رابط مشارك.",
        "cs": "Přidejte film nebo seriál do seznamu ze sdíleného odkazu.",
        "da": "Tilføj en film eller serie til watchlisten fra et delt link.",
        "el": "Πρόσθεσε ταινία ή σειρά στη λίστα από κοινόχρηστο σύνδεσμο.",
        "fi": "Lisää elokuva tai sarja katselulistaan jaetusta linkistä.",
        "he": "הוסף סרט או סדרה לרשימה מקישור משותף.",
        "hi": "साझा लिंक से वॉचलिस्ट में फ़िल्म या शो जोड़ें।",
        "hr": "Dodaj film ili seriju na listu iz dijeljene poveznice.",
        "hu": "Adj filmet vagy sorozatot a listához megosztott linkről.",
        "id": "Tambahkan film atau acara ke watchlist dari tautan bersama.",
        "ja": "共有リンクからウォッチリストに映画やドラマを追加します。",
        "ko": "공유 링크로 관심 목록에 영화나 TV 프로그램을 추가합니다.",
        "ms": "Tambah filem atau rancangan ke senarai tontonan dari pautan dikongsi.",
        "nb": "Legg til en film eller serie i ønskelisten fra en delt lenke.",
        "nl": "Voeg een film of serie toe aan je watchlist via een gedeelde link.",
        "pl": "Dodaj film lub serial do listy z udostępnionego linku.",
        "ro": "Adaugă un film sau un serial pe listă dintr-un link partajat.",
        "ru": "Добавьте фильм или сериал в список по общей ссылке.",
        "sv": "Lägg till en film eller serie i watchlisten från en delad länk.",
        "tr": "Paylaşılan bir bağlantıdan izleme listenize film veya dizi ekleyin.",
        "uk": "Додайте фільм або серіал до списку з спільного посилання.",
        "zh-Hans": "通过共享链接将电影或剧集添加到片单。",
        "zh-Hant": "透過共享連結將電影或劇集加入片單。",
    },
    "Open a movie or TV show in Cronica.": {
        "en": "Open a movie or TV show in Cronica.",
        "de": "Öffne einen Film oder eine Serie in Cronica.",
        "fr": "Ouvrez un film ou une série dans Cronica.",
        "it": "Apri un film o una serie in Cronica.",
        "pt-BR": "Abra um filme ou série no Cronica.",
        "sk": "Otvorte film alebo seriál v Cronica.",
        "es-MX": "Abre una película o serie en Cronica.",
        "es": "Abre una película o serie en Cronica.",
        "ar": "افتح فيلمًا أو مسلسلًا في Cronica.",
        "cs": "Otevřete film nebo seriál v Cronica.",
        "da": "Åbn en film eller serie i Cronica.",
        "el": "Άνοιξε μια ταινία ή σειρά στο Cronica.",
        "fi": "Avaa elokuva tai sarja Cronicassa.",
        "he": "פתח סרט או סדרה ב־Cronica.",
        "hi": "Cronica में कोई फ़िल्म या शो खोलें।",
        "hr": "Otvori film ili seriju u Cronica.",
        "hu": "Nyiss meg egy filmet vagy sorozatot a Cronicában.",
        "id": "Buka film atau acara di Cronica.",
        "ja": "Cronicaで映画やドラマを開きます。",
        "ko": "Cronica에서 영화나 TV 프로그램을 엽니다.",
        "ms": "Buka filem atau rancangan dalam Cronica.",
        "nb": "Åpne en film eller serie i Cronica.",
        "nl": "Open een film of serie in Cronica.",
        "pl": "Otwórz film lub serial w Cronica.",
        "ro": "Deschide un film sau un serial în Cronica.",
        "ru": "Откройте фильм или сериал в Cronica.",
        "sv": "Öppna en film eller serie i Cronica.",
        "tr": "Cronica’da bir film veya dizi açın.",
        "uk": "Відкрийте фільм або серіал у Cronica.",
        "zh-Hans": "在 Cronica 中打开电影或剧集。",
        "zh-Hant": "在 Cronica 中打開電影或劇集。",
    },
    "Open your Cronica watchlist.": {
        "en": "Open your Cronica watchlist.",
        "de": "Öffne deine Cronica-Watchlist.",
        "fr": "Ouvrez votre liste Cronica.",
        "it": "Apri la watchlist di Cronica.",
        "pt-BR": "Abra sua lista do Cronica.",
        "sk": "Otvorte svoj zoznam Cronica.",
        "es-MX": "Abre tu lista de Cronica.",
        "es": "Abre tu lista de Cronica.",
        "ar": "افتح قائمة المشاهدة في Cronica.",
        "cs": "Otevřete svůj seznam Cronica.",
        "da": "Åbn din Cronica-watchlist.",
        "el": "Άνοιξε τη λίστα σου στο Cronica.",
        "fi": "Avaa Cronican katselulistasi.",
        "he": "פתח את רשימת הצפייה של Cronica.",
        "hi": "अपनी Cronica वॉचलिस्ट खोलें।",
        "hr": "Otvori svoju Cronica listu.",
        "hu": "Nyisd meg a Cronica listádat.",
        "id": "Buka watchlist Cronica Anda.",
        "ja": "Cronicaのウォッチリストを開きます。",
        "ko": "Cronica 관심 목록을 엽니다.",
        "ms": "Buka senarai tontonan Cronica anda.",
        "nb": "Åpne Cronica-ønskelisten din.",
        "nl": "Open je Cronica-watchlist.",
        "pl": "Otwórz swoją listę Cronica.",
        "ro": "Deschide lista ta Cronica.",
        "ru": "Откройте свой список Cronica.",
        "sv": "Öppna din Cronica-watchlist.",
        "tr": "Cronica izleme listenizi açın.",
        "uk": "Відкрийте свій список Cronica.",
        "zh-Hans": "打开你的 Cronica 片单。",
        "zh-Hant": "打開你的 Cronica 片單。",
    },
    "Open your watchlist in Cronica.": {
        "en": "Open your watchlist in Cronica.",
        "de": "Öffne deine Watchlist in Cronica.",
        "fr": "Ouvrez votre liste dans Cronica.",
        "it": "Apri la tua watchlist in Cronica.",
        "pt-BR": "Abra sua lista no Cronica.",
        "sk": "Otvorte svoj zoznam v Cronica.",
        "es-MX": "Abre tu lista en Cronica.",
        "es": "Abre tu lista en Cronica.",
        "ar": "افتح قائمة المشاهدة في Cronica.",
        "cs": "Otevřete svůj seznam v Cronica.",
        "da": "Åbn din watchlist i Cronica.",
        "el": "Άνοιξε τη λίστα σου στο Cronica.",
        "fi": "Avaa katselulistasi Cronicassa.",
        "he": "פתח את רשימת הצפייה שלך ב־Cronica.",
        "hi": "Cronica में अपनी वॉचलिस्ट खोलें।",
        "hr": "Otvori svoju listu u Cronica.",
        "hu": "Nyisd meg a listádat a Cronicában.",
        "id": "Buka watchlist Anda di Cronica.",
        "ja": "Cronicaでウォッチリストを開きます。",
        "ko": "Cronica에서 관심 목록을 엽니다.",
        "ms": "Buka senarai tontonan anda dalam Cronica.",
        "nb": "Åpne ønskelisten din i Cronica.",
        "nl": "Open je watchlist in Cronica.",
        "pl": "Otwórz swoją listę w Cronica.",
        "ro": "Deschide lista ta în Cronica.",
        "ru": "Откройте свой список в Cronica.",
        "sv": "Öppna din watchlist i Cronica.",
        "tr": "Cronica’daki izleme listenizi açın.",
        "uk": "Відкрийте свій список у Cronica.",
        "zh-Hans": "在 Cronica 中打开片单。",
        "zh-Hant": "在 Cronica 中打開片單。",
    },
    "Please say which title you mean.": {
        "en": "Please say which title you mean.",
        "de": "Bitte sage, welchen Titel du meinst.",
        "fr": "Veuillez préciser quel titre vous voulez.",
        "it": "Indica quale titolo intendi.",
        "pt-BR": "Diga qual título você quer dizer.",
        "sk": "Povedzte, ktorý titul myslíte.",
        "es-MX": "Di qué título quieres decir.",
        "es": "Di a qué título te refieres.",
        "ar": "يرجى تحديد العنوان المقصود.",
        "cs": "Řekněte, který titul máte na mysli.",
        "da": "Sig venligst hvilken titel du mener.",
        "el": "Πες ποιος τίτλος εννοείς.",
        "fi": "Kerro, mitä nimeä tarkoitat.",
        "he": "אנא אמור לאיזו כותרת התכוונת.",
        "hi": "कृपया बताएं आप किस शीर्षक की बात कर रहे हैं।",
        "hr": "Reci koji naslov misliš.",
        "hu": "Mondd meg, melyik címre gondolsz.",
        "id": "Sebutkan judul yang Anda maksud.",
        "ja": "どの作品か教えてください。",
        "ko": "어떤 작품인지 말씀해 주세요.",
        "ms": "Sila nyatakan tajuk yang dimaksudkan.",
        "nb": "Si hvilken tittel du mener.",
        "nl": "Zeg welke titel je bedoelt.",
        "pl": "Podaj, który tytuł masz na myśli.",
        "ro": "Spune ce titlu ai în vedere.",
        "ru": "Уточните, какое название вы имеете в виду.",
        "sv": "Säg vilken titel du menar.",
        "tr": "Hangi yapımı kastettiğini söyle.",
        "uk": "Уточніть, яку назву ви маєте на увазі.",
        "zh-Hans": "请说明你指的是哪部作品。",
        "zh-Hant": "請說明你指的是哪部作品。",
    },
    "Cronica couldn't find that movie or TV show.": {
        "en": "Cronica couldn't find that movie or TV show.",
        "de": "Cronica konnte diesen Film oder diese Serie nicht finden.",
        "fr": "Cronica n’a pas trouvé ce film ou cette série.",
        "it": "Cronica non ha trovato quel film o quella serie.",
        "pt-BR": "O Cronica não encontrou esse filme ou série.",
        "sk": "Cronica nenašla tento film ani seriál.",
        "es-MX": "Cronica no encontró esa película o serie.",
        "es": "Cronica no encontró esa película o serie.",
        "ar": "تعذر على Cronica العثور على ذلك الفيلم أو المسلسل.",
        "cs": "Cronica nenašla tento film ani seriál.",
        "da": "Cronica kunne ikke finde den film eller serie.",
        "el": "Το Cronica δεν βρήκε αυτή την ταινία ή σειρά.",
        "fi": "Cronica ei löytänyt kyseistä elokuvaa tai sarjaa.",
        "he": "Cronica לא מצא את הסרט או הסדרה.",
        "hi": "Cronica वह फ़िल्म या शो नहीं ढूँढ सका।",
        "hr": "Cronica nije pronašla taj film ili seriju.",
        "hu": "A Cronica nem találta azt a filmet vagy sorozatot.",
        "id": "Cronica tidak menemukan film atau acara itu.",
        "ja": "Cronicaはその映画やドラマを見つけられませんでした。",
        "ko": "Cronica에서 해당 영화나 TV 프로그램을 찾지 못했습니다.",
        "ms": "Cronica tidak jumpa filem atau rancangan itu.",
        "nb": "Cronica fant ikke den filmen eller serien.",
        "nl": "Cronica kon die film of serie niet vinden.",
        "pl": "Cronica nie znalazła tego filmu ani serialu.",
        "ro": "Cronica nu a găsit acel film sau serial.",
        "ru": "Cronica не нашла этот фильм или сериал.",
        "sv": "Cronica kunde inte hitta den filmen eller serien.",
        "tr": "Cronica o film veya diziyi bulamadı.",
        "uk": "Cronica не знайшла цей фільм або серіал.",
        "zh-Hans": "Cronica 找不到这部电影或剧集。",
        "zh-Hant": "Cronica 找不到這部電影或劇集。",
    },
    "That title isn't on your watchlist.": {
        "en": "That title isn't on your watchlist.",
        "de": "Dieser Titel ist nicht auf deiner Watchlist.",
        "fr": "Ce titre n’est pas dans votre liste.",
        "it": "Quel titolo non è nella tua watchlist.",
        "pt-BR": "Esse título não está na sua lista.",
        "sk": "Tento titul nie je vo vašom zozname.",
        "es-MX": "Ese título no está en tu lista.",
        "es": "Ese título no está en tu lista.",
        "ar": "هذا العنوان ليس في قائمة المشاهدة.",
        "cs": "Tento titul není ve vašem seznamu.",
        "da": "Den titel er ikke på din watchlist.",
        "el": "Αυτός ο τίτλος δεν είναι στη λίστα σου.",
        "fi": "Tuo nimi ei ole katselulistallasi.",
        "he": "הכותרת הזו אינה ברשימת הצפייה שלך.",
        "hi": "वह शीर्षक आपकी वॉचलिस्ट पर नहीं है।",
        "hr": "Taj naslov nije na tvojoj listi.",
        "hu": "Ez a cím nincs a listádon.",
        "id": "Judul itu tidak ada di watchlist Anda.",
        "ja": "その作品はウォッチリストにありません。",
        "ko": "해당 작품이 관심 목록에 없습니다.",
        "ms": "Tajuk itu tiada dalam senarai tontonan anda.",
        "nb": "Den tittelen er ikke på ønskelisten din.",
        "nl": "Die titel staat niet op je watchlist.",
        "pl": "Tego tytułu nie ma na Twojej liście.",
        "ro": "Titlul respectiv nu este pe lista ta.",
        "ru": "Этого названия нет в вашем списке.",
        "sv": "Den titeln finns inte i din watchlist.",
        "tr": "Bu yapım izleme listenizde yok.",
        "uk": "Цієї назви немає у вашому списку.",
        "zh-Hans": "该作品不在你的片单中。",
        "zh-Hant": "該作品不在你的片單中。",
    },
    "That title is already on your watchlist.": {
        "en": "That title is already on your watchlist.",
        "de": "Dieser Titel ist bereits auf deiner Watchlist.",
        "fr": "Ce titre est déjà dans votre liste.",
        "it": "Quel titolo è già nella tua watchlist.",
        "pt-BR": "Esse título já está na sua lista.",
        "sk": "Tento titul už je vo vašom zozname.",
        "es-MX": "Ese título ya está en tu lista.",
        "es": "Ese título ya está en tu lista.",
        "ar": "هذا العنوان موجود بالفعل في قائمة المشاهدة.",
        "cs": "Tento titul už je ve vašem seznamu.",
        "da": "Den titel er allerede på din watchlist.",
        "el": "Αυτός ο τίτλος είναι ήδη στη λίστα σου.",
        "fi": "Tuo nimi on jo katselulistallasi.",
        "he": "הכותרת הזו כבר ברשימת הצפייה שלך.",
        "hi": "वह शीर्षक पहले से आपकी वॉचलिस्ट पर है।",
        "hr": "Taj naslov je već na tvojoj listi.",
        "hu": "Ez a cím már a listádon van.",
        "id": "Judul itu sudah ada di watchlist Anda.",
        "ja": "その作品はすでにウォッチリストにあります。",
        "ko": "해당 작품이 이미 관심 목록에 있습니다.",
        "ms": "Tajuk itu sudah ada dalam senarai tontonan anda.",
        "nb": "Den tittelen er allerede på ønskelisten din.",
        "nl": "Die titel staat al op je watchlist.",
        "pl": "Ten tytuł jest już na Twojej liście.",
        "ro": "Titlul respectiv este deja pe lista ta.",
        "ru": "Это название уже есть в вашем списке.",
        "sv": "Den titeln finns redan i din watchlist.",
        "tr": "Bu yapım zaten izleme listenizde.",
        "uk": "Ця назва вже є у вашому списку.",
        "zh-Hans": "该作品已在你的片单中。",
        "zh-Hant": "該作品已在你的片單中。",
    },
    "That title hasn't been released yet.": {
        "en": "That title hasn't been released yet.",
        "de": "Dieser Titel wurde noch nicht veröffentlicht.",
        "fr": "Ce titre n’est pas encore sorti.",
        "it": "Quel titolo non è ancora uscito.",
        "pt-BR": "Esse título ainda não foi lançado.",
        "sk": "Tento titul ešte nebol vydaný.",
        "es-MX": "Ese título aún no se ha estrenado.",
        "es": "Ese título aún no se ha estrenado.",
        "ar": "لم يُصدر هذا العنوان بعد.",
        "cs": "Tento titul ještě nebyl vydán.",
        "da": "Den titel er ikke udgivet endnu.",
        "el": "Αυτός ο τίτλος δεν έχει κυκλοφορήσει ακόμη.",
        "fi": "Tuo nimi ei ole vielä julkaistu.",
        "he": "הכותרת הזו עדיין לא יצאה.",
        "hi": "वह शीर्षक अभी रिलीज़ नहीं हुआ है।",
        "hr": "Taj naslov još nije objavljen.",
        "hu": "Ez a cím még nem jelent meg.",
        "id": "Judul itu belum dirilis.",
        "ja": "その作品はまだ公開されていません。",
        "ko": "해당 작품이 아직 출시되지 않았습니다.",
        "ms": "Tajuk itu belum dikeluarkan.",
        "nb": "Den tittelen er ikke utgitt ennå.",
        "nl": "Die titel is nog niet uitgebracht.",
        "pl": "Ten tytuł nie został jeszcze wydany.",
        "ro": "Titlul respectiv nu a fost încă lansat.",
        "ru": "Это название ещё не вышло.",
        "sv": "Den titeln har inte haft premiär än.",
        "tr": "Bu yapım henüz yayımlanmadı.",
        "uk": "Ця назва ще не вийшла.",
        "zh-Hans": "该作品尚未上映。",
        "zh-Hant": "該作品尚未上映。",
    },
    "Cronica couldn't reach TMDb. Try again in a moment.": {
        "en": "Cronica couldn't reach TMDb. Try again in a moment.",
        "de": "Cronica konnte TMDb nicht erreichen. Versuche es gleich noch einmal.",
        "fr": "Cronica n’a pas pu joindre TMDb. Réessayez dans un instant.",
        "it": "Cronica non riesce a raggiungere TMDb. Riprova tra poco.",
        "pt-BR": "O Cronica não conseguiu acessar o TMDb. Tente de novo em instantes.",
        "sk": "Cronica sa nedostala k TMDb. Skúste to o chvíľu znova.",
        "es-MX": "Cronica no pudo conectar con TMDb. Inténtalo en un momento.",
        "es": "Cronica no pudo conectar con TMDb. Inténtalo en un momento.",
        "ar": "تعذر على Cronica الوصول إلى TMDb. حاول مجددًا بعد لحظات.",
        "cs": "Cronica se nedostala k TMDb. Zkuste to za chvíli znovu.",
        "da": "Cronica kunne ikke nå TMDb. Prøv igen om et øjeblik.",
        "el": "Το Cronica δεν μπόρεσε να συνδεθεί με το TMDb. Δοκίμασε ξανά σε λίγο.",
        "fi": "Cronica ei saanut yhteyttä TMDb:hen. Yritä hetken kuluttua uudelleen.",
        "he": "Cronica לא הצליח להגיע ל־TMDb. נסה שוב בעוד רגע.",
        "hi": "Cronica TMDb तक नहीं पहुँच सका। थोड़ी देर बाद फिर कोशिश करें।",
        "hr": "Cronica nije mogla dohvatiti TMDb. Pokušaj opet za trenutak.",
        "hu": "A Cronica nem érte el a TMDb-t. Próbáld újra egy pillanat múlva.",
        "id": "Cronica tidak dapat menghubungi TMDb. Coba lagi sebentar.",
        "ja": "CronicaはTMDbに接続できませんでした。しばらくして再試行してください。",
        "ko": "Cronica가 TMDb에 연결하지 못했습니다. 잠시 후 다시 시도하세요.",
        "ms": "Cronica tidak dapat menghubungi TMDb. Cuba lagi sebentar.",
        "nb": "Cronica nådde ikke TMDb. Prøv igjen om litt.",
        "nl": "Cronica kon TMDb niet bereiken. Probeer het zo opnieuw.",
        "pl": "Cronica nie mogła połączyć się z TMDb. Spróbuj za chwilę.",
        "ro": "Cronica nu a putut contacta TMDb. Încearcă din nou imediat.",
        "ru": "Cronica не удалось связаться с TMDb. Попробуйте чуть позже.",
        "sv": "Cronica kunde inte nå TMDb. Försök igen om en stund.",
        "tr": "Cronica TMDb’ye ulaşamadı. Biraz sonra yeniden dene.",
        "uk": "Cronica не змогла зв’язатися з TMDb. Спробуйте за мить.",
        "zh-Hans": "Cronica 无法连接 TMDb。请稍后再试。",
        "zh-Hant": "Cronica 無法連線 TMDb。請稍後再試。",
    },
    "Opening search in Cronica.": {
        "en": "Opening search in Cronica.",
        "de": "Öffne die Suche in Cronica.",
        "fr": "Ouverture de la recherche dans Cronica.",
        "it": "Apertura della ricerca in Cronica.",
        "pt-BR": "Abrindo a pesquisa no Cronica.",
        "sk": "Otvára sa vyhľadávanie v Cronica.",
        "es-MX": "Abriendo la búsqueda en Cronica.",
        "es": "Abriendo la búsqueda en Cronica.",
        "ar": "جارٍ فتح البحث في Cronica.",
        "cs": "Otevírá se hledání v Cronica.",
        "da": "Åbner søgning i Cronica.",
        "el": "Άνοιγμα αναζήτησης στο Cronica.",
        "fi": "Avataan haku Cronicassa.",
        "he": "פותח חיפוש ב־Cronica.",
        "hi": "Cronica में खोज खोली जा रही है।",
        "hr": "Otvaram pretraživanje u Cronica.",
        "hu": "Keresés megnyitása a Cronicában.",
        "id": "Membuka pencarian di Cronica.",
        "ja": "Cronicaの検索を開いています。",
        "ko": "Cronica에서 검색을 엽니다.",
        "ms": "Membuka carian dalam Cronica.",
        "nb": "Åpner søk i Cronica.",
        "nl": "Zoeken in Cronica openen.",
        "pl": "Otwieranie wyszukiwania w Cronica.",
        "ro": "Se deschide căutarea în Cronica.",
        "ru": "Открываю поиск в Cronica.",
        "sv": "Öppnar sökning i Cronica.",
        "tr": "Cronica’da arama açılıyor.",
        "uk": "Відкриваю пошук у Cronica.",
        "zh-Hans": "正在打开 Cronica 搜索。",
        "zh-Hant": "正在打開 Cronica 搜尋。",
    },
    "Opening your watchlist in Cronica.": {
        "en": "Opening your watchlist in Cronica.",
        "de": "Öffne deine Watchlist in Cronica.",
        "fr": "Ouverture de votre liste dans Cronica.",
        "it": "Apertura della watchlist in Cronica.",
        "pt-BR": "Abrindo sua lista no Cronica.",
        "sk": "Otvára sa váš zoznam v Cronica.",
        "es-MX": "Abriendo tu lista en Cronica.",
        "es": "Abriendo tu lista en Cronica.",
        "ar": "جارٍ فتح قائمة المشاهدة في Cronica.",
        "cs": "Otevírá se váš seznam v Cronica.",
        "da": "Åbner din watchlist i Cronica.",
        "el": "Άνοιγμα της λίστας σου στο Cronica.",
        "fi": "Avataan katselulistaasi Cronicassa.",
        "he": "פותח את רשימת הצפייה שלך ב־Cronica.",
        "hi": "Cronica में आपकी वॉचलिस्ट खोली जा रही है।",
        "hr": "Otvaram tvoju listu u Cronica.",
        "hu": "Listád megnyitása a Cronicában.",
        "id": "Membuka watchlist Anda di Cronica.",
        "ja": "Cronicaのウォッチリストを開いています。",
        "ko": "Cronica에서 관심 목록을 엽니다.",
        "ms": "Membuka senarai tontonan anda dalam Cronica.",
        "nb": "Åpner ønskelisten din i Cronica.",
        "nl": "Je watchlist in Cronica openen.",
        "pl": "Otwieranie Twojej listy w Cronica.",
        "ro": "Se deschide lista ta în Cronica.",
        "ru": "Открываю ваш список в Cronica.",
        "sv": "Öppnar din watchlist i Cronica.",
        "tr": "Cronica izleme listeniz açılıyor.",
        "uk": "Відкриваю ваш список у Cronica.",
        "zh-Hans": "正在打开你的 Cronica 片单。",
        "zh-Hant": "正在打開你的 Cronica 片單。",
    },
    "Opening Up Next in Cronica.": {
        "en": "Opening Up Next in Cronica.",
        "de": "Öffne Als Nächstes in Cronica.",
        "fr": "Ouverture de À suivre dans Cronica.",
        "it": "Apertura di In programma in Cronica.",
        "pt-BR": "Abrindo A seguir no Cronica.",
        "sk": "Otvára sa Ďalej v Cronica.",
        "es-MX": "Abriendo A continuación en Cronica.",
        "es": "Abriendo A continuación en Cronica.",
        "ar": "جارٍ فتح التالي في Cronica.",
        "cs": "Otevírá se Další v Cronica.",
        "da": "Åbner Næste i Cronica.",
        "el": "Άνοιγμα των Επόμενων στο Cronica.",
        "fi": "Avataan Seuraavaksi Cronicassa.",
        "he": "פותח את הבא בתור ב־Cronica.",
        "hi": "Cronica में आगे क्या खोला जा रहा है।",
        "hr": "Otvaram Sljedeće u Cronica.",
        "hu": "Következők megnyitása a Cronicában.",
        "id": "Membuka Selanjutnya di Cronica.",
        "ja": "Cronicaの次に観るを開いています。",
        "ko": "Cronica에서 다음에 볼 것을 엽니다.",
        "ms": "Membuka Seterusnya dalam Cronica.",
        "nb": "Åpner Neste i Cronica.",
        "nl": "Hierna in Cronica openen.",
        "pl": "Otwieranie Dalej w Cronica.",
        "ro": "Se deschide Urmează în Cronica.",
        "ru": "Открываю «Дальше» в Cronica.",
        "sv": "Öppnar Härnäst i Cronica.",
        "tr": "Cronica’da Sıradakiler açılıyor.",
        "uk": "Відкриваю «Далі» в Cronica.",
        "zh-Hans": "正在打开 Cronica 的接下来。",
        "zh-Hant": "正在打開 Cronica 的接下來。",
    },
    "Added %@ to your watchlist.": {
        "en": "Added %@ to your watchlist.",
        "de": "%@ wurde zu deiner Watchlist hinzugefügt.",
        "fr": "%@ a été ajouté à votre liste.",
        "it": "%@ aggiunto alla watchlist.",
        "pt-BR": "%@ adicionado à sua lista.",
        "sk": "%@ bol pridaný do zoznamu.",
        "es-MX": "Se agregó %@ a tu lista.",
        "es": "Se añadió %@ a tu lista.",
        "ar": "تمت إضافة %@ إلى قائمة المشاهدة.",
        "cs": "%@ bylo přidáno do seznamu.",
        "da": "%@ er føjet til din watchlist.",
        "el": "Προστέθηκε το %@ στη λίστα σου.",
        "fi": "%@ lisättiin katselulistaan.",
        "he": "%@ נוסף לרשימת הצפייה שלך.",
        "hi": "%@ आपकी वॉचलिस्ट में जोड़ दिया गया।",
        "hr": "%@ je dodan na tvoju listu.",
        "hu": "%@ hozzáadva a listádhoz.",
        "id": "%@ ditambahkan ke watchlist Anda.",
        "ja": "%@をウォッチリストに追加しました。",
        "ko": "%@을(를) 관심 목록에 추가했습니다.",
        "ms": "%@ ditambah ke senarai tontonan anda.",
        "nb": "%@ er lagt til i ønskelisten din.",
        "nl": "%@ is toegevoegd aan je watchlist.",
        "pl": "Dodano %@ do Twojej listy.",
        "ro": "%@ a fost adăugat pe lista ta.",
        "ru": "%@ добавлено в ваш список.",
        "sv": "%@ lades till i din watchlist.",
        "tr": "%@ izleme listenize eklendi.",
        "uk": "%@ додано до вашого списку.",
        "zh-Hans": "已将%@加入片单。",
        "zh-Hant": "已將%@加入片單。",
    },
    "Removed %@ from your watchlist.": {
        "en": "Removed %@ from your watchlist.",
        "de": "%@ wurde von deiner Watchlist entfernt.",
        "fr": "%@ a été retiré de votre liste.",
        "it": "%@ rimosso dalla watchlist.",
        "pt-BR": "%@ removido da sua lista.",
        "sk": "%@ bol odstránený zo zoznamu.",
        "es-MX": "Se quitó %@ de tu lista.",
        "es": "Se quitó %@ de tu lista.",
        "ar": "تمت إزالة %@ من قائمة المشاهدة.",
        "cs": "%@ bylo odebráno ze seznamu.",
        "da": "%@ er fjernet fra din watchlist.",
        "el": "Αφαιρέθηκε το %@ από τη λίστα σου.",
        "fi": "%@ poistettiin katselulistasta.",
        "he": "%@ הוסר מרשימת הצפייה שלך.",
        "hi": "%@ आपकी वॉचलिस्ट से हटा दिया गया।",
        "hr": "%@ je uklonjen s tvoje liste.",
        "hu": "%@ eltávolítva a listádról.",
        "id": "%@ dihapus dari watchlist Anda.",
        "ja": "%@をウォッチリストから削除しました。",
        "ko": "%@을(를) 관심 목록에서 제거했습니다.",
        "ms": "%@ dibuang dari senarai tontonan anda.",
        "nb": "%@ er fjernet fra ønskelisten din.",
        "nl": "%@ is verwijderd uit je watchlist.",
        "pl": "Usunięto %@ z Twojej listy.",
        "ro": "%@ a fost eliminat de pe lista ta.",
        "ru": "%@ удалено из вашего списка.",
        "sv": "%@ togs bort från din watchlist.",
        "tr": "%@ izleme listenizden kaldırıldı.",
        "uk": "%@ видалено з вашого списку.",
        "zh-Hans": "已从片单移除%@。",
        "zh-Hant": "已從片單移除%@。",
    },
    "Marked %@ as watched.": {
        "en": "Marked %@ as watched.",
        "de": "%@ wurde als gesehen markiert.",
        "fr": "%@ a été marqué comme vu.",
        "it": "%@ segnato come visto.",
        "pt-BR": "%@ marcado como assistido.",
        "sk": "%@ bol označený ako pozretý.",
        "es-MX": "Se marcó %@ como visto.",
        "es": "Se marcó %@ como visto.",
        "ar": "تم تعليم %@ كمشاهَد.",
        "cs": "%@ bylo označeno jako zhlédnuté.",
        "da": "%@ er markeret som set.",
        "el": "Το %@ σημάνθηκε ως προβληθέν.",
        "fi": "%@ merkittiin katsotuksi.",
        "he": "%@ סומן כנצפה.",
        "hi": "%@ को देखा गया चिह्नित किया गया।",
        "hr": "%@ je označen kao pogledan.",
        "hu": "%@ megnézettként jelölve.",
        "id": "%@ ditandai sebagai ditonton.",
        "ja": "%@を視聴済みにしました。",
        "ko": "%@을(를) 시청함으로 표시했습니다.",
        "ms": "%@ ditanda sebagai ditonton.",
        "nb": "%@ er merket som sett.",
        "nl": "%@ is gemarkeerd als bekeken.",
        "pl": "Oznaczono %@ jako obejrzane.",
        "ro": "%@ a fost marcat ca vizionat.",
        "ru": "%@ отмечено как просмотренное.",
        "sv": "%@ markerades som sett.",
        "tr": "%@ izlendi olarak işaretlendi.",
        "uk": "%@ позначено як переглянуте.",
        "zh-Hans": "已将%@标记为已看。",
        "zh-Hant": "已將%@標記為已看。",
    },
    "Opening %@ in Cronica.": {
        "en": "Opening %@ in Cronica.",
        "de": "Öffne %@ in Cronica.",
        "fr": "Ouverture de %@ dans Cronica.",
        "it": "Apertura di %@ in Cronica.",
        "pt-BR": "Abrindo %@ no Cronica.",
        "sk": "Otvára sa %@ v Cronica.",
        "es-MX": "Abriendo %@ en Cronica.",
        "es": "Abriendo %@ en Cronica.",
        "ar": "جارٍ فتح %@ في Cronica.",
        "cs": "Otevírá se %@ v Cronica.",
        "da": "Åbner %@ i Cronica.",
        "el": "Άνοιγμα του %@ στο Cronica.",
        "fi": "Avataan %@ Cronicassa.",
        "he": "פותח את %@ ב־Cronica.",
        "hi": "Cronica में %@ खोला जा रहा है।",
        "hr": "Otvaram %@ u Cronica.",
        "hu": "%@ megnyitása a Cronicában.",
        "id": "Membuka %@ di Cronica.",
        "ja": "Cronicaで%@を開いています。",
        "ko": "Cronica에서 %@을(를) 엽니다.",
        "ms": "Membuka %@ dalam Cronica.",
        "nb": "Åpner %@ i Cronica.",
        "nl": "%@ in Cronica openen.",
        "pl": "Otwieranie %@ w Cronica.",
        "ro": "Se deschide %@ în Cronica.",
        "ru": "Открываю %@ в Cronica.",
        "sv": "Öppnar %@ i Cronica.",
        "tr": "Cronica’da %@ açılıyor.",
        "uk": "Відкриваю %@ у Cronica.",
        "zh-Hans": "正在 Cronica 中打开%@。",
        "zh-Hant": "正在 Cronica 中打開%@。",
    },
    "Any": {
        "en": "Any", "de": "Beliebig", "fr": "Tous", "it": "Qualsiasi", "pt-BR": "Qualquer",
        "sk": "Ľubovoľné", "es-MX": "Cualquiera", "es": "Cualquiera", "ar": "أي",
        "cs": "Libovolné", "da": "Alle", "el": "Οποιοδήποτε", "fi": "Mikä tahansa",
        "he": "הכל", "hi": "कोई भी", "hr": "Bilo koje", "hu": "Bármely", "id": "Apa saja",
        "ja": "すべて", "ko": "전체", "ms": "Mana-mana", "nb": "Alle", "nl": "Alle",
        "pl": "Dowolne", "ro": "Oricare", "ru": "Любой", "sv": "Alla", "tr": "Herhangi",
        "uk": "Будь-який", "zh-Hans": "全部", "zh-Hant": "全部",
    },
    "Person": {
        "en": "Person", "de": "Person", "fr": "Personne", "it": "Persona", "pt-BR": "Pessoa",
        "sk": "Osoba", "es-MX": "Persona", "es": "Persona", "ar": "شخص",
        "cs": "Osoba", "da": "Person", "el": "Πρόσωπο", "fi": "Henkilö",
        "he": "אדם", "hi": "व्यक्ति", "hr": "Osoba", "hu": "Személy", "id": "Orang",
        "ja": "人物", "ko": "인물", "ms": "Orang", "nb": "Person", "nl": "Persoon",
        "pl": "Osoba", "ro": "Persoană", "ru": "Человек", "sv": "Person", "tr": "Kişi",
        "uk": "Особа", "zh-Hans": "人物", "zh-Hant": "人物",
    },
    "Watchlist Title": {
        "en": "Watchlist Title", "de": "Watchlist-Titel", "fr": "Titre de la liste",
        "it": "Titolo watchlist", "pt-BR": "Título da lista", "sk": "Titul zo zoznamu",
        "es-MX": "Título de la lista", "es": "Título de la lista", "ar": "عنوان قائمة المشاهدة",
        "cs": "Titul ze seznamu", "da": "Watchlist-titel", "el": "Τίτλος λίστας",
        "fi": "Katselulistan nimi", "he": "כותרת ברשימה", "hi": "वॉचलिस्ट शीर्षक",
        "hr": "Naslov s liste", "hu": "Lista cím", "id": "Judul watchlist",
        "ja": "ウォッチリストの作品", "ko": "관심 목록 작품", "ms": "Tajuk senarai tontonan",
        "nb": "Ønskeliste-tittel", "nl": "Watchlist-titel", "pl": "Tytuł z listy",
        "ro": "Titlu din listă", "ru": "Название из списка", "sv": "Watchlist-titel",
        "tr": "İzleme listesi yapımı", "uk": "Назва зі списку",
        "zh-Hans": "片单作品", "zh-Hant": "片單作品",
    },
    "Up Next Episode": {
        "en": "Up Next Episode", "de": "Nächste Episode", "fr": "Épisode à suivre",
        "it": "Episodio in programma", "pt-BR": "Episódio a seguir", "sk": "Ďalšia epizóda",
        "es-MX": "Episodio a continuación", "es": "Episodio a continuación", "ar": "الحلقة التالية",
        "cs": "Další epizoda", "da": "Næste episode", "el": "Επόμενο επεισόδιο",
        "fi": "Seuraava jakso", "he": "הפרק הבא", "hi": "अगला एपिसोड",
        "hr": "Sljedeća epizoda", "hu": "Következő epizód", "id": "Episode selanjutnya",
        "ja": "次のエピソード", "ko": "다음 에피소드", "ms": "Episod seterusnya",
        "nb": "Neste episode", "nl": "Volgende aflevering", "pl": "Następny odcinek",
        "ro": "Episodul următor", "ru": "Следующий эпизод", "sv": "Nästa avsnitt",
        "tr": "Sıradaki bölüm", "uk": "Наступний епізод",
        "zh-Hans": "下一集", "zh-Hant": "下一集",
    },
    "Search Result": {
        "en": "Search Result", "de": "Suchergebnis", "fr": "Résultat de recherche",
        "it": "Risultato di ricerca", "pt-BR": "Resultado da pesquisa", "sk": "Výsledok hľadania",
        "es-MX": "Resultado de búsqueda", "es": "Resultado de búsqueda", "ar": "نتيجة البحث",
        "cs": "Výsledek hledání", "da": "Søgeresultat", "el": "Αποτέλεσμα αναζήτησης",
        "fi": "Hakutulos", "he": "תוצאת חיפוש", "hi": "खोज परिणाम",
        "hr": "Rezultat pretraživanja", "hu": "Keresési találat", "id": "Hasil pencarian",
        "ja": "検索結果", "ko": "검색 결과", "ms": "Hasil carian",
        "nb": "Søkeresultat", "nl": "Zoekresultaat", "pl": "Wynik wyszukiwania",
        "ro": "Rezultatul căutării", "ru": "Результат поиска", "sv": "Sökresultat",
        "tr": "Arama sonucu", "uk": "Результат пошуку",
        "zh-Hans": "搜索结果", "zh-Hant": "搜尋結果",
    },
    "S%d · E%d": {
        "en": "S%d · E%d", "de": "S%d · E%d", "fr": "S%d · E%d", "it": "S%d · E%d",
        "pt-BR": "T%d · E%d", "sk": "S%d · E%d", "es-MX": "T%d · E%d", "es": "T%d · E%d",
        "ar": "م%d · ح%d", "cs": "S%d · E%d", "da": "S%d · E%d", "el": "Σ%d · Ε%d",
        "fi": "K%d · J%d", "he": "ע%d · פ%d", "hi": "सी%d · ए%d", "hr": "S%d · E%d",
        "hu": "É%d · R%d", "id": "M%d · E%d", "ja": "S%d · E%d", "ko": "S%d · E%d",
        "ms": "S%d · E%d", "nb": "S%d · E%d", "nl": "S%d · A%d", "pl": "S%d · O%d",
        "ro": "S%d · E%d", "ru": "С%d · Э%d", "sv": "S%d · A%d", "tr": "S%d · B%d",
        "uk": "С%d · Е%d", "zh-Hans": "第%d季 · 第%d集", "zh-Hant": "第%d季 · 第%d集",
    },
    "Query": {
        "en": "Query", "de": "Suchbegriff", "fr": "Requête", "it": "Query", "pt-BR": "Consulta",
        "sk": "Dopyt", "es-MX": "Consulta", "es": "Consulta", "ar": "استعلام",
        "cs": "Dotaz", "da": "Forespørgsel", "el": "Ερώτημα", "fi": "Haku",
        "he": "שאילתה", "hi": "क्वेरी", "hr": "Upit", "hu": "Lekérdezés", "id": "Kueri",
        "ja": "検索語", "ko": "검색어", "ms": "Pertanyaan", "nb": "Spørring", "nl": "Zoekopdracht",
        "pl": "Zapytanie", "ro": "Interogare", "ru": "Запрос", "sv": "Fråga", "tr": "Sorgu",
        "uk": "Запит", "zh-Hans": "查询", "zh-Hant": "查詢",
    },
    "Browse Cronica Shortcuts": {
        "en": "Browse Cronica Shortcuts", "de": "Cronica-Kurzbefehle durchsuchen",
        "fr": "Parcourir les raccourcis Cronica", "it": "Sfoglia i comandi di Cronica",
        "pt-BR": "Explorar atalhos do Cronica", "sk": "Prehliadať skratky Cronica",
        "es-MX": "Explorar atajos de Cronica", "es": "Explorar atajos de Cronica",
        "ar": "تصفح اختصارات Cronica", "cs": "Procházet zkratky Cronica",
        "da": "Gennemse Cronica-genveje", "el": "Περιήγηση στις συντομεύσεις Cronica",
        "fi": "Selaa Cronican pikakomentoja", "he": "עיין בקיצורי הדרך של Cronica",
        "hi": "Cronica शॉर्टकट ब्राउज़ करें", "hr": "Pregledaj Cronica prečace",
        "hu": "Cronica parancsok böngészése", "id": "Jelajahi pintasan Cronica",
        "ja": "Cronicaのショートカットを見る", "ko": "Cronica 단축어 살펴보기",
        "ms": "Semak imbas pintasan Cronica", "nb": "Bla gjennom Cronica-snarveier",
        "nl": "Cronica-opdrachten bekijken", "pl": "Przeglądaj skróty Cronica",
        "ro": "Răsfoiește comenzile Cronica", "ru": "Просмотреть команды Cronica",
        "sv": "Bläddra bland Cronica-genvägar", "tr": "Cronica kısayollarına göz at",
        "uk": "Переглянути команди Cronica", "zh-Hans": "浏览 Cronica 快捷指令", "zh-Hant": "瀏覽 Cronica 捷徑",
    },
    "Search Titles": {
        "en": "Search Titles", "de": "Titel suchen", "fr": "Rechercher des titres",
        "it": "Cerca titoli", "pt-BR": "Pesquisar títulos", "sk": "Hľadať tituly",
        "es-MX": "Buscar títulos", "es": "Buscar títulos", "ar": "البحث عن عناوين",
        "cs": "Hledat tituly", "da": "Søg efter titler", "el": "Αναζήτηση τίτλων",
        "fi": "Hae nimiä", "he": "חפש כותרות", "hi": "शीर्षक खोजें",
        "hr": "Traži naslove", "hu": "Címek keresése", "id": "Cari judul",
        "ja": "作品を検索", "ko": "작품 검색", "ms": "Cari tajuk",
        "nb": "Søk etter titler", "nl": "Titels zoeken", "pl": "Szukaj tytułów",
        "ro": "Caută titluri", "ru": "Искать названия", "sv": "Sök titlar",
        "tr": "Yapım ara", "uk": "Шукати назви", "zh-Hans": "搜索作品", "zh-Hant": "搜尋作品",
    },
}
